<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_New project_avatar avatar-small circle</name>
   <tag></tag>
   <elementGuidId>e9772538-4f94-4fbf-9080-4bab1b0a6c15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.avatar.avatar-small.circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='@hasnanfl'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aeaead52-5ebf-4425-bc76-0104ab6cd297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://avatars.githubusercontent.com/u/66814022?s=40&amp;v=4</value>
      <webElementGuid>22f3413b-82aa-4570-9e90-b1f80496fa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>@hasnanfl</value>
      <webElementGuid>1f26be79-66d9-48f0-9868-9dd97d515677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>56c0fd94-8d1a-4c5b-be87-694016322eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a5e2e733-fc39-4bbb-aeb3-b39c3dbe53d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a0a0bbcf-a7a8-434d-91ce-ba825dcec4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view-component</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>adfbaf0e-0248-45f2-a0ae-350aa90c86e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar avatar-small circle</value>
      <webElementGuid>6b8e8288-c6da-4c56-9f9b-cc00503702c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;logged-in env-production page-responsive full-width intent-mouse&quot;]/div[@class=&quot;position-relative js-header-wrapper&quot;]/header[@class=&quot;Header js-details-container Details px-3 px-md-4 px-lg-5 flex-wrap flex-md-nowrap&quot;]/div[@class=&quot;Header-item position-relative mr-0 d-none d-md-flex&quot;]/details[@class=&quot;details-overlay details-reset js-feature-preview-indicator-container&quot;]/summary[@class=&quot;Header-link&quot;]/img[@class=&quot;avatar avatar-small circle&quot;]</value>
      <webElementGuid>3f330b23-2277-4c73-9a57-e142e29c3d34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='@hasnanfl'])[2]</value>
      <webElementGuid>ccaec827-4ef7-4a28-aa1b-3d13bc9e7d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//summary/img</value>
      <webElementGuid>9dc7da28-d5fe-4d1f-bab9-dc518bbb3c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://avatars.githubusercontent.com/u/66814022?s=40&amp;v=4' and @alt = '@hasnanfl']</value>
      <webElementGuid>f307a60a-00f7-4e57-8f76-225251581763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
