<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New project_feature-preview-indicator _723196</name>
   <tag></tag>
   <elementGuidId>f3a56e69-9239-460b-869e-9329ba522add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.feature-preview-indicator.js-feature-preview-indicator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[7]/details/summary/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a6c8f716-3c42-47c2-b213-d77b66179bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feature-preview-indicator js-feature-preview-indicator</value>
      <webElementGuid>a2230943-9c56-4e0a-873b-3d2a22e9be30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;logged-in env-production page-responsive full-width intent-mouse&quot;]/div[@class=&quot;position-relative js-header-wrapper&quot;]/header[@class=&quot;Header js-details-container Details px-3 px-md-4 px-lg-5 flex-wrap flex-md-nowrap&quot;]/div[@class=&quot;Header-item position-relative mr-0 d-none d-md-flex&quot;]/details[@class=&quot;details-overlay details-reset js-feature-preview-indicator-container&quot;]/summary[@class=&quot;Header-link&quot;]/span[@class=&quot;feature-preview-indicator js-feature-preview-indicator&quot;]</value>
      <webElementGuid>14887ef2-4125-4e47-b49a-889bea980365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/details/summary/span</value>
      <webElementGuid>80146905-7097-40e8-959e-d28a945630dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
