<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Close</name>
   <tag></tag>
   <elementGuidId>699939f4-979f-46f7-a587-2edf90d0315b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.closeBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='hide_popup();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0484b78c-2917-49d0-9a87-3499c5516f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d39a9f30-535e-482b-9072-3ad927ade4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>closeBtn</value>
      <webElementGuid>9f1caa4e-229b-4881-b2d9-9e6717c8a9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hide_popup();</value>
      <webElementGuid>62ce258c-31e8-4b2e-b525-3e9bf7661fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>102f1ce2-0415-48d1-bb91-4a59b7df8dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mm-0&quot;)/section[1]/div[@class=&quot;popupWrapper&quot;]/div[@class=&quot;popupBox&quot;]/div[@class=&quot;popupcontent&quot;]/a[@class=&quot;closeBtn&quot;]</value>
      <webElementGuid>b5b049fa-8957-4697-9e41-d635d9dfd51a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='hide_popup();']</value>
      <webElementGuid>c6746e3b-e5e2-44e5-9356-84c59eba8d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mm-0']/section/div[6]/div[2]/div/a[2]</value>
      <webElementGuid>61cbbc9d-b87a-465c-87e0-cd7e0c6536b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Close')]</value>
      <webElementGuid>672d5686-8805-4277-a485-e917655dd143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lowongan Kerja'])[2]/following::a[2]</value>
      <webElementGuid>09c8d8b1-eef5-49f7-8d1e-e8339e100d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biz Devl./Partner Relationship Manager-3DP'])[1]/following::a[3]</value>
      <webElementGuid>aef69aca-516f-4f93-b181-b60af103dbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you for submit your email.. blablabla....'])[1]/preceding::a[1]</value>
      <webElementGuid>be16f83e-1107-4252-99f6-af9f8ff57f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::a[1]</value>
      <webElementGuid>4688ee98-e5b2-42b3-9700-4cc5c5448a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>761022b1-282b-451b-a81f-8157999ede1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[20]</value>
      <webElementGuid>67aee7d2-5e20-46f7-9d65-431ad05e0070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>fa18f9af-bb3c-461f-ae17-da7e7f5ee486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>cdf65b29-876d-4994-8d9a-d34f7507e8c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
