<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lowongan Kerja</name>
   <tag></tag>
   <elementGuidId>69b24938-26ad-4693-8e5c-55e7b9469f4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.def_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mm-0']/section/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8a5b809a-d5ad-4c51-aee1-f0438aa80d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://career.astragraphia.co.id/jobs</value>
      <webElementGuid>23373d81-2d4f-4ec9-b10e-914449e8eb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>def_btn</value>
      <webElementGuid>4c999449-f18e-4945-a232-bb225f0f19e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lowongan Kerja</value>
      <webElementGuid>27090b2e-64e2-44f8-aa73-498707aa9087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mm-0&quot;)/section[1]/div[@class=&quot;section_banner&quot;]/div[@class=&quot;sb_info&quot;]/a[@class=&quot;def_btn&quot;]</value>
      <webElementGuid>b2dd2f22-6764-4d58-a3fe-253214487552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mm-0']/section/div/div[2]/a</value>
      <webElementGuid>73d4c006-a156-41ca-8893-789126087775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lowongan Kerja')]</value>
      <webElementGuid>67acf7a9-5b9b-4252-89d4-c066234bfdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temukan Potensi Anda'])[1]/following::a[1]</value>
      <webElementGuid>558119a4-f1e3-433e-9ca0-4713f275f71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::a[3]</value>
      <webElementGuid>eef9435f-bf04-40d3-9fe5-8eebe01a70f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengapa Bekerja di Astragraphia ?'])[1]/preceding::a[1]</value>
      <webElementGuid>b8ac9eb8-c754-4160-9a93-006d6b48c9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='prev'])[1]/preceding::a[7]</value>
      <webElementGuid>287e6fff-1585-466d-acd6-ee4a5d6e3f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lowongan Kerja']/parent::*</value>
      <webElementGuid>2c09029b-273d-47ea-805c-54e6545cdfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://career.astragraphia.co.id/jobs')])[2]</value>
      <webElementGuid>41693b8e-8a19-4e61-9a19-a359b2ccb655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>c5cc1da8-4e08-4935-9faf-08f16f3183d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://career.astragraphia.co.id/jobs' and (text() = 'Lowongan Kerja' or . = 'Lowongan Kerja')]</value>
      <webElementGuid>1b5d1298-a892-4e09-9bb9-0e5812f580bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
