<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_MV Start () - Gaho ()   Itaewon Class ( ) OST Pt. 2 -  ENG SUB</name>
   <tag></tag>
   <elementGuidId>fef605be-c33a-4d78-b3a3-82059d602bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//yt-formatted-string[@id='video-title'])[17]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>0223bca0-e574-46b1-805e-446cb60b9235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>video-title</value>
      <webElementGuid>16530725-c490-442b-bb76-16d5cf675223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-rich-grid-media</value>
      <webElementGuid>abd9eb53-8bc0-4370-a586-8b0e028a80c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>[MV] Start (시작) - Gaho (가호)  | Itaewon Class (이태원 클라쓰) OST Pt. 2 - 조이서 [ENG SUB] by phii1244 2 years ago 3 minutes, 36 seconds 38,498,236 views</value>
      <webElementGuid>f48b3ba2-81e9-404c-bf1f-79c69f1dec7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[MV] Start (시작) - Gaho (가호)  | Itaewon Class (이태원 클라쓰) OST Pt. 2 - 조이서 [ENG SUB]</value>
      <webElementGuid>6a32957d-debe-44eb-9f37-21af12257238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-manager&quot;)/ytd-browse[@class=&quot;style-scope ytd-page-manager&quot;]/ytd-two-column-browse-results-renderer[@class=&quot;style-scope ytd-browse grid-disabled&quot;]/div[@id=&quot;primary&quot;]/ytd-rich-grid-renderer[@class=&quot;style-scope ytd-two-column-browse-results-renderer&quot;]/div[@id=&quot;contents&quot;]/ytd-rich-grid-row[@class=&quot;style-scope ytd-rich-grid-renderer&quot;]/div[@id=&quot;contents&quot;]/ytd-rich-item-renderer[@class=&quot;style-scope ytd-rich-grid-row&quot;]/div[@id=&quot;content&quot;]/ytd-rich-grid-media[@class=&quot;style-scope ytd-rich-item-renderer&quot;]/div[@id=&quot;dismissible&quot;]/div[@id=&quot;details&quot;]/div[@id=&quot;meta&quot;]/h3[@class=&quot;style-scope ytd-rich-grid-media&quot;]/a[@id=&quot;video-title-link&quot;]/yt-formatted-string[@id=&quot;video-title&quot;]</value>
      <webElementGuid>917d83cf-af81-4109-8fc6-74686e39b648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//yt-formatted-string[@id='video-title'])[17]</value>
      <webElementGuid>b5667aef-6c68-425a-bfeb-5b764aae0d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='video-title-link']/yt-formatted-string)[17]</value>
      <webElementGuid>345be9a2-3cc0-47cc-b54a-9cbf58bf38b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Now playing'])[17]/following::yt-formatted-string[1]</value>
      <webElementGuid>bf0e7678-a95b-4a8b-8c4e-c3357fea3095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='•'])[17]/following::yt-formatted-string[1]</value>
      <webElementGuid>0de57e73-4387-4804-b389-b040f552a731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='phii1244'])[1]/preceding::yt-formatted-string[1]</value>
      <webElementGuid>76ee159d-7ae8-462e-91db-694f9bf6bfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ytd-rich-grid-row[6]/div/ytd-rich-item-renderer[2]/div/ytd-rich-grid-media/div/div[2]/div/h3/a/yt-formatted-string</value>
      <webElementGuid>0bdfbb63-725f-4b9b-b6d4-9be2b67c617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'video-title' and (text() = '[MV] Start (시작) - Gaho (가호)  | Itaewon Class (이태원 클라쓰) OST Pt. 2 - 조이서 [ENG SUB]' or . = '[MV] Start (시작) - Gaho (가호)  | Itaewon Class (이태원 클라쓰) OST Pt. 2 - 조이서 [ENG SUB]')]</value>
      <webElementGuid>cfbde13d-419b-4da2-9c96-581ef482eb29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
