<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Device Verification Code_otp</name>
   <tag></tag>
   <elementGuidId>dcae2e4a-29bd-4b4a-be09-b72e62cc636d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>247e94cf-06d9-4db8-bdde-8a6611b01a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44ff7066-3801-4cf1-a476-20daaf5ba005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>d52f0dcb-32e3-43b6-81d2-b802ea7722ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>1ef53c61-fbd4-4a2f-bc7e-10f4cb5fd6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aa9715e8-595c-4b1a-bb4d-42732c3f812e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>ffded76f-0eb7-40b3-a18a-f37dd6901c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-block js-verification-code-input-auto-submit</value>
      <webElementGuid>16d740e2-895c-4163-b632-062634227652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>82516c2e-1458-462c-bc65-02d8f59fdff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>([0-9]{6})|([0-9a-fA-F]{5}-?[0-9a-fA-F]{5})</value>
      <webElementGuid>0bc86ea9-337a-42f1-b2fd-47a4c1ef8c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>6-digit code</value>
      <webElementGuid>7cbd544c-9f05-46e9-8f19-31dccfea54f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp&quot;)</value>
      <webElementGuid>ebced457-da0f-442f-8018-cb760c9444d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp']</value>
      <webElementGuid>9f1c3f8e-1133-495a-bda9-06cc9490314f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/div[3]/div[2]/div[2]/form/input[2]</value>
      <webElementGuid>2e75a0a3-03ca-4899-b78a-5c64f223ff65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>0dedaf35-784d-451b-8264-3acaad9e7460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'otp' and @id = 'otp' and @placeholder = '6-digit code']</value>
      <webElementGuid>483698d0-a26c-4e4d-90c8-027a09e17023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
