<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kebijakan Privasi iQIYI_passport-inpu_6c5f26</name>
   <tag></tag>
   <elementGuidId>cf803250-9161-4297-af51-ce92ef5d76ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.passport-input__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>179ceac9-8ede-4d77-b785-de8df1dde0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56084bec-9948-4b8e-b57a-8fdf3fb5c54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>edbd88da-9741-47be-9035-bd6f4b8facf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>on-bind:value</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>5c993e7a-080d-47e3-b750-154259eed1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>passport-input__input</value>
      <webElementGuid>f3525b92-cc05-4fed-89f4-9f5ec8c8d834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-sdk-container&quot;)/div[@class=&quot;global-passport passport-login passport-long global-all-passport&quot;]/div[@class=&quot;passport-wrapper&quot;]/div[@class=&quot;passport-content&quot;]/div[@class=&quot;passport__inner&quot;]/div[1]/div[1]/div[@class=&quot;passport-input&quot;]/div[1]/div[@class=&quot;passport-input-group focus&quot;]/label[@class=&quot;passport-input__wrapper&quot;]/input[@class=&quot;passport-input__input&quot;]</value>
      <webElementGuid>5cade761-76ba-42be-8c31-e96d640272e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>baff4997-e9d4-4338-9b4e-f29138bdeb01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-sdk-container']/div/div/div[2]/div/div/div/div[3]/div/div/label/input</value>
      <webElementGuid>8d9a06e0-b0cd-419a-b65b-8b87a8320c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>0436928d-0afb-4911-be22-5e6be817e18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d1966417-4912-4ff3-b47d-a423ae0b2c28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
