<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Daftar</name>
   <tag></tag>
   <elementGuidId>955e5c1a-5f38-4444-8eab-f7556d41e75c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.passport-login-tip__link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-sdk-container']/div/div/div[2]/div/div/div[4]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8cd34e41-f6dc-4346-bf4c-4facf5c2e20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>c70fd282-c72d-4606-bf24-179ca383d551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>passport-login-tip__link</value>
      <webElementGuid>2389832b-f8cf-4b37-a24b-0cc754ffbb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>71696af5-d722-4d9d-b239-f0db10569433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-sdk-container&quot;)/div[@class=&quot;global-passport passport-login passport-long global-all-passport&quot;]/div[@class=&quot;passport-wrapper autoheight&quot;]/div[@class=&quot;passport-content&quot;]/div[@class=&quot;passport__inner&quot;]/div[@class=&quot;passport-first-wrapper&quot;]/div[@class=&quot;passport-footer&quot;]/div[@class=&quot;passport-login-tip&quot;]/span[@class=&quot;passport-login-tip__link&quot;]</value>
      <webElementGuid>8ab2e68c-5082-424a-823b-7fad8b7269ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-sdk-container']/div/div/div[2]/div/div/div[4]/div/span[2]</value>
      <webElementGuid>bdcfddb1-564d-45e7-83ce-a98bb9c1a5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak punya akun?'])[1]/following::span[1]</value>
      <webElementGuid>166c30aa-334a-41bd-941e-51228fce53a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketentuan Layanan'])[1]/following::span[2]</value>
      <webElementGuid>13a96ff9-05f5-4aa1-a870-298bb346d8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>9806bab5-9611-4e69-ae8c-961ef348d92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span[2]</value>
      <webElementGuid>33f0adb8-eb97-4fa4-abe9-f52839f440b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@href = 'javascript:void(0)' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>a873595e-c71a-41e6-989a-91c01686216e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
