<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>de4cc85c-b167-4ba9-8d0a-c0578e153a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.area-code > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi iQIYI'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>3f0d9986-2559-4cff-a64a-beb630d02ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>5e2701e9-21b5-4a0d-827d-5574db6d86fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>b0df3f69-df18-4302-a449-250e873603c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>e53218fe-6865-4e76-a727-36ac1d6968e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-sdk-container&quot;)/div[@class=&quot;global-passport passport-login passport-long global-all-passport&quot;]/div[@class=&quot;passport-wrapper&quot;]/div[@class=&quot;passport-content&quot;]/div[@class=&quot;passport__inner&quot;]/div[1]/div[1]/div[@class=&quot;passport-input&quot;]/div[1]/div[@class=&quot;passport-input-group&quot;]/div[1]/div[@class=&quot;area-code&quot;]/svg[1]</value>
      <webElementGuid>07f75185-2073-4d4a-956b-e7c4ae8f55fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi iQIYI'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>489bd971-98db-415d-9598-2e80b3f406c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='简体中文'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>410e1ad7-ce6a-4e93-bd25-6b954198aa3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombor Telefon Bimbit'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>bda35692-f11f-49ef-873e-fe39421d99da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>86187c80-9731-463a-a1e2-a6d18888fec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
