<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_JanuariFebruariMaretAprilMeiJuniJuli_13de9b</name>
   <tag></tag>
   <elementGuidId>e5377d11-66f9-4a3e-b2fe-e54223362561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SELECTOR_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SELECTOR_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f050040e-d136-45ac-a2d3-145dd43950cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf28b5c6-93f1-4ddd-b5b5-773272a66cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>SELECTOR_1_LABEL</value>
      <webElementGuid>fd759b02-7594-4609-aaf6-6a0562d3a6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r-30o5oe r-1niwhzg r-17gur6a r-1yadl64 r-18jsvk2 r-1loqt21 r-37j5jr r-1inkyih r-rjixqe r-crgep1 r-1wzrnnt r-1ny4l3l r-t60dpp r-xd6kpl r-1pn2ns4 r-ttdzmv</value>
      <webElementGuid>4eb6084a-188e-44ff-b95e-9d39757c1ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SELECTOR_1</value>
      <webElementGuid>8802cbcb-7d42-48c5-a2ef-24d19fd508e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JanuariFebruariMaretAprilMeiJuniJuliAgustusSeptemberOktoberNovemberDesember</value>
      <webElementGuid>f3c0991f-8bc8-45b3-b665-bc4974b08e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SELECTOR_1&quot;)</value>
      <webElementGuid>07873ef8-afb0-4c9a-bcba-f88784cb5414</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SELECTOR_1']</value>
      <webElementGuid>339954db-8e7b-4477-ba78-77ca27618adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layers']/div[2]/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[4]/div[3]/div/div/select</value>
      <webElementGuid>b40335dd-7f34-4e12-b71a-78128a5de7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulan'])[1]/following::select[1]</value>
      <webElementGuid>cf3ae4ed-989c-47d5-88de-5a8a2f4e3f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal lahir'])[1]/following::select[1]</value>
      <webElementGuid>e10561c3-9181-4652-8772-5dc930c5c592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hari'])[1]/preceding::select[1]</value>
      <webElementGuid>ba3387ef-3f32-4f1a-92ba-db56f0011804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[1]/preceding::select[2]</value>
      <webElementGuid>ff5c50dd-7992-4309-87fe-138290292863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c2b9ea6a-1fe7-4c9a-a728-fb27f3fdba9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SELECTOR_1' and (text() = 'JanuariFebruariMaretAprilMeiJuniJuliAgustusSeptemberOktoberNovemberDesember' or . = 'JanuariFebruariMaretAprilMeiJuniJuliAgustusSeptemberOktoberNovemberDesember')]</value>
      <webElementGuid>3b800a4f-0fe6-4d1d-95b2-e9b9bb68082d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
