<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Indonesian</name>
   <tag></tag>
   <elementGuidId>38b4849b-c601-400b-bd84-4400746153c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div/c-wiz/div[2]/c-wiz/div[2]/div/div[3]/div/div[2]/div[53]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dbca3de8-1552-4aca-8029-ee49f64b6260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Llmcnf</value>
      <webElementGuid>7b4cf138-e0ce-42b9-a890-dc8f14e55760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>Lm8Uhb</value>
      <webElementGuid>4e3b724a-6318-4420-9124-56410fce6fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesian</value>
      <webElementGuid>d145189a-688b-4a5b-9449-4732acbb897f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf RvYhPd BIdYQ aL9XFd&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;WFnNle&quot;]/c-wiz[@class=&quot;MOkH4e BSw7K iYelWb yF6Zo DNkvFf&quot;]/div[@class=&quot;OlSOob&quot;]/c-wiz[@class=&quot;QsA0jb DNkvFf&quot;]/div[@class=&quot;ccvoYb EjH7wc&quot;]/div[@class=&quot;aCQag&quot;]/c-wiz[@class=&quot;kHGNJd DNkvFf&quot;]/div[2]/c-wiz[@class=&quot;bvzp8c DlHcnf&quot;]/div[@class=&quot;ykTHSe&quot;]/div[@class=&quot;pEyuac X4hZJc&quot;]/div[@class=&quot;dykxn MeCBDd j33Gae&quot;]/div[@class=&quot;vSUSRc&quot;]/div[@class=&quot;F29iQc&quot;]/div[@class=&quot;qSb8Pe&quot;]/div[@class=&quot;Llmcnf&quot;]</value>
      <webElementGuid>de6f3c50-6c4a-4350-b57f-df5e3ae06897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div/c-wiz/div[2]/c-wiz/div[2]/div/div[3]/div/div[2]/div[53]/div[2]</value>
      <webElementGuid>2d1405a3-838a-4e82-b16b-605001401699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ilocano'])[2]/following::div[3]</value>
      <webElementGuid>8aa469a1-545b-4a11-af1c-9a781f8ac9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Igbo'])[2]/following::div[6]</value>
      <webElementGuid>6004a535-274b-4c14-a838-4846935d360c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Irish'])[2]/preceding::div[2]</value>
      <webElementGuid>5034e733-9fbe-483a-96f3-fa40bae09686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italian'])[2]/preceding::div[5]</value>
      <webElementGuid>190d3d68-e7b2-454d-ba99-8212f5f3c3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[53]/div[2]</value>
      <webElementGuid>50273f09-c9f6-4f4c-86cb-2c75606cf285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Indonesian' or . = 'Indonesian')]</value>
      <webElementGuid>154d9627-df98-445d-a84f-4ca9061c0921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
