<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_English_VfPpkd-YVzG2b</name>
   <tag></tag>
   <elementGuidId>33a157b0-1ed3-47a3-a2d0-235b293a18c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i8 > span.VfPpkd-YVzG2b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i8']/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a40b2cd9-b998-4a59-8d11-083837eaad02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VfPpkd-YVzG2b</value>
      <webElementGuid>ece79cdf-c3ac-4984-9177-be2d3af74cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>ksKsZd</value>
      <webElementGuid>278bcdf4-d679-461e-8b87-67831a9c0168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i8&quot;)/span[@class=&quot;VfPpkd-YVzG2b&quot;]</value>
      <webElementGuid>6fcd8bb0-4fb6-403b-b199-81de3298ca6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='i8']/span[3]</value>
      <webElementGuid>ee7ae450-f3e8-4b5d-bc2e-0af98fa0c86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[3]</value>
      <webElementGuid>c5517527-f6f4-4543-9b2d-7bdbe8b95930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
