<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Authorize gitlabhq</name>
   <tag></tag>
   <elementGuidId>f57ba4ff-6cd1-4bb6-9bb8-f17ee408af82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-oauth-authorize-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js-oauth-authorize-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fadbc10d-c00f-40d3-83fd-e356d033a0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-click</name>
      <type>Main</type>
      <value>oauth_application_authorization</value>
      <webElementGuid>19609916-4b2d-4068-a681-1b084e862a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-dimensions</name>
      <type>Main</type>
      <value>marketplace_listing_id:,came_from_marketplace:false,paid_marketplace_plan_purchased:false</value>
      <webElementGuid>a3529106-84a3-4430-aa0d-365fd652bd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-click</name>
      <type>Main</type>
      <value>Oauth, oauth application authorized, oauth_application_id:62872; listing_id:; came_from_integrations_directory:false; came_from_marketplace:false; paid_marketplace_plan_purchased:false; marketplace_listing_id:</value>
      <webElementGuid>e2753117-2a90-4ae0-ae01-0ba577cc4dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>90fd64d8-d219-40ca-a3bd-9c1b78414a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>authorize</value>
      <webElementGuid>2dc3b208-99af-4c06-9312-b930391eb32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2f354db1-eb16-4540-902e-bfa0946a89d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-oauth-authorize-btn</value>
      <webElementGuid>be097fdc-193e-4c2f-98d1-80baec0dfe55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary width-full ws-normal</value>
      <webElementGuid>75621301-98ea-4653-89c1-d82756a0f84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorize gitlabhq</value>
      <webElementGuid>3772fd9c-89e6-4e2b-8d6b-0deeaa163a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-oauth-authorize-btn&quot;)</value>
      <webElementGuid>58169529-3e57-4c6d-aa8b-a9f7ebaae8ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js-oauth-authorize-btn']</value>
      <webElementGuid>57a3c9f6-4a23-4011-8778-e73d63682e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-pjax-container']/div/div[2]/div/div[2]/div/form/div/button[2]</value>
      <webElementGuid>c692fb5b-178d-49d7-8701-eca188413dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>5cf2f31d-1a3e-4135-8619-de77590c38a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[2]</value>
      <webElementGuid>2446ea67-c0b7-44fd-b4a2-3036ba878bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://gitlab.com'])[1]/preceding::button[1]</value>
      <webElementGuid>2ee9ca33-9ca5-4f9a-9890-355a99c3ff24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Authorize gitlabhq']/parent::*</value>
      <webElementGuid>61cde1e7-7e9d-4383-82f6-faad636dc8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>a406bb1b-63e8-4709-b6f1-ab96ffeafc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'authorize' and @id = 'js-oauth-authorize-btn' and (text() = 'Authorize gitlabhq' or . = 'Authorize gitlabhq')]</value>
      <webElementGuid>c96cc3b1-2966-4c5a-9824-30e0ba7966a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
